{
  "Default": {
    "--settings-visibility": "1",
    "--main-bg-visibility": "1",
    "--main-bg-shadow-visibility": "1",
    "--custom-dark-mode-visibility": "1",
    "--audio-visibility": "1",
    "--freq-visibility": "1",
    "--tag-visibility": "1",
    "--external-links-visibility": "1",
    "--pitch-position-visibility": "1",
    "--settings-visibility-header": "1",
    "--main-bg-1050-visibility": "1",
    "--main-bg-shadow-1050-visibility": "0",
    "--custom-dm-header-visibility": "1",
    "--audio-header-visibility": "1",
    "--freq-header-visibility": "1",
    "--enable-animations": "true",
    "--word-sentence-default-expanded": "false",
    "--audio-sentence-default-expanded": "false",
    "--hint-default-expanded": "false",
    "--translation-default-expanded": "false",
    "--notes-default-expanded": "false",
    "--collect-glossary-images": "false",
    "--no-duplicate-kana": "false",
    "--mute-sentence-audio": "false",
    "--base-size": "clamp(19px, 3vw, 24px)",
    "--base-line-height": "1.5",
    "--bold-highlight": "0",
    "--serif": "\"Hiragino Mincho ProN\", \"Klee One\", klee, \"Noto Serif CJK JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sans": "\"Hiragino Kaku Gothic ProN\", \"Noto Sans CJK JP\", notosansjp, \"Segoe UI\", sans-serif",
    "--sentence-alignment": "center",
    "--word-size-base": "2.5rem",
    "--word-size-4": "2.1rem",
    "--word-size-5": "2.0rem",
    "--word-size-6": "1.7rem",
    "--word-size-7": "1.6rem",
    "--word-size-8": "1.3rem",
    "--word-size-9": "1.15rem",
    "--reading-position": "below",
    "--dynamic-furigana-size": "0",
    "--furigana-size": "1rem",
    "--furigana-height": "0.0rem",
    "--sentence-furigana-display": "1",
    "--sentence-furigana-height": "0.0rem",
    "--sentence-size": "1.3rem",
    "--sentence-eng-size": "0.8rem",
    "--definition-size": "0.8rem",
    "--misc-info-size": "15px",
    "--tag-font-size": "0.7rem",
    "--frequency-size": "20px",
    "--frequency-content-size": "14px",
    "--border-radius-sm": "4px",
    "--border-radius-ms": "5px",
    "--border-radius-md": "10px",
    "--border-radius-lg": "12px",
    "--tag-border-radius": "5px",
    "--card-max-width": "800px",
    "--front-top-offset": "104px",
    "--back-top-offset": "26px",
    "--button-size": "20px",
    "--picture-height": "220px",
    "--picture-height-small": "330px",
    "--lightbox-nav-width": "100px",
    "--external-links-icon-size": "25px",
    "--frequency-max-height": "500px",
    "--base-transition": "0.3s ease",
    "--fast-transition": "0.2s ease",
    "--spacing-xs": "2px",
    "--spacing-sm": "3px",
    "--spacing-ms": "8px",
    "--spacing-md": "10px",
    "--spacing-lg": "15px",
    "--spacing-xl": "20px",
    "--spacing-xxl": "24px",
    "--spacing-xxxl": "34px",
    "--base-padding": "20px",
    "--dictionary-collapse": "1",
    "--dictionary-max-height": "390px",
    "--definition-title-visibility": "1",
    "--glossary-title-visibility": "1",
    "--dictionary-colorizer": "1",
    "--dict-bg-enabled": "1",
    "--dict-back-bg": "1",
    "--dict-bg-opacity": "0.03",
    "--dict-border-width": "5px",
    "--jitendex-hide-examples": "0",
    "--jitendex-hide-info-gloss": "0",
    "--jitendex-hide-xref": "0",
    "--jitendex-hide-graphic": "0",
    "--jitendex-hide-notes": "0",
    "--jitendex-hide-antonyms": "0",
    "--jitendex-hide-forms": "1",
    "--jitendex-hide-attribution": "1",
    "--pitch-style": "default",
    "--pitch-colors": "true",
    "--sentence-pitch-highlight": "false",
    "--only-kana-pitch-size": "0.08em",
    "--enable-kanji-hover": "true",
    "--kanji-hover-sentence-visibility": "1",
    "--kanji-hover-auto-quote": "true",
    "--kanji-hover-word-font": "var(--serif)",
    "--kanji-hover-word-size": "1rem",
    "--kanji-hover-word-reading-size": "0.65rem",
    "--kanji-hover-pitch-colors": "true",
    "--kanji-hover-pitch-highlight": "true",
    "--grid-gap": "var(--spacing-md)",
    "--grid-column-min-width": "390px",
    "--grid-order": "1",
    "--vertical-grid-order": "0",
    "--horizontal-grid-large": "1",
    "--vertical-grid-large": "0",
    "--horizontal-grid-medium": "1",
    "--vertical-grid-medium": "0",
    "--horizontal-grid-small": "0",
    "--vertical-grid-small": "1",
    "--enable-backdrop-layout": "0",
    "--backdrop-style": "1",
    "--backdrop-dynamic-height": "0",
    "--bd-card-bg-front-offset": "55px",
    "--bd-word-bg-front-offset": "119px",
    "--word-background-box": "0",
    "--backdrop-opacity": "0.5",
    "--backdrop-background-height": "250px",
    "--bd-text-shadow-color-light": "255, 255, 255",
    "--bd-text-shadow-color": "0, 0, 0",
    "--bd-text-shadow-opacity-light": "0.6",
    "--bd-text-shadow-opacity": "0.6",
    "--card-background-fade": "1",
    "--card-fade-strength": "50%",
    "--word-background-fade": "0",
    "--word-fade-strength": "60%",
    "--enable-custom-offsets": "0",
    "--bd-word-bg-front-offset-1050": "5.45rem",
    "--bd-card-bg-front-offset-1050": "2.8rem",
    "--bd-word-bg-front-offset-mobile": "11.5rem",
    "--misc-info-default-expanded": "false",
    "--misc-info-above": "false",
    "--bold-misc-info": "0",
    "--misc-info-alignment": "center",
    "--misc-info-bg-visibility": "1",
    "--blur-nsfw-picture": "true",
    "--mute-nsfw-audio": "true",
    "--toggle-settings-key": "p",
    "--scene-replay-shortcut-key": "w",
    "--toggle-custom-dark-mode-key": "c",
    "--toggle-picture-lightbox-key": "q",
    "--toggle-picture-lightbox-grid-key": "shift+q",
    "--toggle-image-key": "l",
    "--text-light": "#020202",
    "--text": "#fcfcfc",
    "--light-highlight": "#E20033",
    "--dark-highlight": "#FEC8D8",
    "--light-devoiced-color": "RoyalBlue",
    "--dark-devoiced-color": "cornflowerBlue",
    "--freq-text-light": "rgba(105, 105, 105, 0.3)",
    "--freq-text": "rgba(255, 255, 255, 0.2)",
    "--tag-bg-light": "rgba(0, 0, 0, 0.03)",
    "--tag-bg": "rgba(0, 0, 0, 0.1)",
    "--tag-color-light": "rgba(105, 105, 105, 0.26)",
    "--tag-color": "rgba(255, 255, 255, 0.21)",
    "--tag-color-hover-light": "rgba(255, 255, 255, 1)",
    "--tag-color-hover": "rgba(255, 255, 255, 1)",
    "--external-links-bg-light": "rgba(0, 0, 0, 0.1)",
    "--external-links-bg": "rgba(0, 0, 0, 0.4)",
    "--misc-info-text-light": "rgba(105, 105, 105, 0.26)",
    "--misc-info-text": "rgba(255, 255, 255, 0.21)",
    "--misc-info-text-hover-light": "rgba(255, 255, 255, 1)",
    "--misc-info-text-hover": "rgba(255, 255, 255, 1)",
    "--misc-info-bg-light": "rgba(0, 0, 0, 0.03)",
    "--misc-info-bg": "rgba(0, 0, 0, 0.1)",
    "--misc-info-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--misc-info-bg-hover": "rgba(0, 0, 0, 0.3)",
    "--svg-color-light": "rgba(105, 105, 105, 0.3)",
    "--svg-color": "rgba(255, 255, 255, 0.2)",
    "--svg-hover-light": "rgba(255, 255, 255, 1)",
    "--svg-hover": "rgba(255, 255, 255, 1)",
    "--buttons-bg-light": "rgba(0, 0, 0, 0.03)",
    "--buttons-bg": "rgba(0, 0, 0, 0.1)",
    "--buttons-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--buttons-bg-hover": "rgba(0, 0, 0, 0.63)",
    "--background-light": "#f5f5f5",
    "--background": "#2c2c2c",
    "--card-bg-light": "rgba(255, 255, 255, 0.4)",
    "--card-bg": "rgba(0, 0, 0, 0.4)",
    "--card-shadow-light": "rgba(0, 0, 0, 0.05)",
    "--card-shadow": "rgba(0, 0, 0, 0.3)",
    "--lightbox-bg-light": "rgba(0, 0, 0, 0.8)",
    "--lightbox-bg": "rgba(0, 0, 0, 0.8)",
    "--pitch-position-bg-light": "rgba(255, 255, 255, 0.8)",
    "--pitch-position-bg": "rgba(0, 0, 0, 0.2)",
    "--pitch-red-light": "#D62839",
    "--pitch-red": "#F5436D",
    "--pitch-blue-light": "#3474FF",
    "--pitch-blue": "#39C1FF",
    "--pitch-orange-light": "#FF6E03",
    "--pitch-orange": "#fca311",
    "--pitch-green-light": "#2BAF7E",
    "--pitch-green": "#40D4A6",
    "--pitch-purple-light": "#8A5EDE",
    "--pitch-purple": "#afa2ff",
    "--word-bg-light": "rgba(0, 0, 0, 0.03)",
    "--word-bg": "rgba(0, 0, 0, 0.3)",
    "--picture-bg-light": "rgba(0, 0, 0, 0.03)",
    "--picture-bg": "rgba(0, 0, 0, 0.3)",
    "--notes-bg-light": "rgba(0, 0, 0, 0.03)",
    "--notes-bg": "rgba(0, 0, 0, 0.3)",
    "--definition-bg-light": "rgba(0, 0, 0, 0.03)",
    "--definition-bg": "rgba(0, 0, 0, 0.3)",
    "--frequency-bg-light": "rgba(255, 255, 255, 0.8)",
    "--frequency-bg": "rgba(0, 0, 0, 0.63)",
    "user-custom-css": ""
  },
  "My Preset 1": {
    "--settings-visibility": "1",
    "--main-bg-visibility": "1",
    "--main-bg-shadow-visibility": "1",
    "--custom-dark-mode-visibility": "1",
    "--audio-visibility": "1",
    "--freq-visibility": "1",
    "--tag-visibility": "1",
    "--external-links-visibility": "1",
    "--pitch-position-visibility": "1",
    "--settings-visibility-header": "1",
    "--main-bg-1050-visibility": "1",
    "--main-bg-shadow-1050-visibility": "1",
    "--custom-dm-header-visibility": "1",
    "--audio-header-visibility": "1",
    "--freq-header-visibility": "1",
    "--enable-animations": "true",
    "--word-sentence-default-expanded": "false",
    "--audio-sentence-default-expanded": "false",
    "--hint-default-expanded": "false",
    "--translation-default-expanded": "false",
    "--notes-default-expanded": "false",
    "--collect-glossary-images": "true",
    "--no-duplicate-kana": "true",
    "--mute-sentence-audio": "false",
    "--base-size": "clamp(19px, 3vw, 24px)",
    "--base-line-height": "1.5",
    "--bold-highlight": "1",
    "--serif": "\"Hiragino Mincho ProN\", \"Klee One\", klee, \"Noto Serif CJK JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sans": "\"Hiragino Kaku Gothic ProN\", \"Noto Sans CJK JP\", notosansjp, \"Segoe UI\", sans-serif",
    "--sentence-alignment": "center",
    "--word-size-base": "2.5rem",
    "--word-size-4": "2.1rem",
    "--word-size-5": "2.0rem",
    "--word-size-6": "1.7rem",
    "--word-size-7": "1.6rem",
    "--word-size-8": "1.3rem",
    "--word-size-9": "1.15rem",
    "--reading-position": "below",
    "--dynamic-furigana-size": "0",
    "--furigana-size": "1rem",
    "--furigana-height": "0.0rem",
    "--sentence-furigana-display": "1",
    "--sentence-furigana-height": "0.0rem",
    "--sentence-size": "1.3rem",
    "--sentence-eng-size": "0.8rem",
    "--definition-size": "0.8rem",
    "--misc-info-size": "15px",
    "--tag-font-size": "0.7rem",
    "--frequency-size": "20px",
    "--frequency-content-size": "14px",
    "--border-radius-sm": "4px",
    "--border-radius-ms": "5px",
    "--border-radius-md": "10px",
    "--border-radius-lg": "12px",
    "--tag-border-radius": "5px",
    "--card-max-width": "800px",
    "--front-top-offset": "104px",
    "--back-top-offset": "26px",
    "--button-size": "20px",
    "--picture-height": "220px",
    "--picture-height-small": "330px",
    "--lightbox-nav-width": "100px",
    "--external-links-icon-size": "25px",
    "--frequency-max-height": "500px",
    "--base-transition": "0.3s ease",
    "--fast-transition": "0.2s ease",
    "--spacing-xs": "2px",
    "--spacing-sm": "3px",
    "--spacing-ms": "8px",
    "--spacing-md": "10px",
    "--spacing-lg": "15px",
    "--spacing-xl": "20px",
    "--spacing-xxl": "24px",
    "--spacing-xxxl": "34px",
    "--base-padding": "20px",
    "--dictionary-collapse": "1",
    "--dictionary-max-height": "390px",
    "--definition-title-visibility": "1",
    "--glossary-title-visibility": "1",
    "--dictionary-colorizer": "1",
    "--dict-bg-enabled": "1",
    "--dict-back-bg": "1",
    "--dict-bg-opacity": "0.03",
    "--dict-border-width": "5px",
    "--jitendex-hide-examples": "0",
    "--jitendex-hide-info-gloss": "0",
    "--jitendex-hide-xref": "0",
    "--jitendex-hide-graphic": "0",
    "--jitendex-hide-notes": "0",
    "--jitendex-hide-antonyms": "0",
    "--jitendex-hide-forms": "1",
    "--jitendex-hide-attribution": "1",
    "--pitch-style": "default",
    "--pitch-colors": "true",
    "--sentence-pitch-highlight": "false",
    "--only-kana-pitch-size": "0.08em",
    "--enable-kanji-hover": "true",
    "--kanji-hover-sentence-visibility": "1",
    "--kanji-hover-auto-quote": "true",
    "--kanji-hover-word-font": "var(--serif)",
    "--kanji-hover-word-size": "1rem",
    "--kanji-hover-word-reading-size": "0.65rem",
    "--kanji-hover-pitch-colors": "true",
    "--kanji-hover-pitch-highlight": "true",
    "--grid-gap": "var(--spacing-lg)",
    "--grid-column-min-width": "390px",
    "--grid-order": "1",
    "--vertical-grid-order": "0",
    "--horizontal-grid-large": "1",
    "--vertical-grid-large": "0",
    "--horizontal-grid-medium": "1",
    "--vertical-grid-medium": "0",
    "--horizontal-grid-small": "0",
    "--vertical-grid-small": "1",
    "--enable-backdrop-layout": "0",
    "--backdrop-style": "1",
    "--backdrop-dynamic-height": "0",
    "--bd-card-bg-front-offset": "55px",
    "--bd-word-bg-front-offset": "119px",
    "--word-background-box": "0",
    "--backdrop-opacity": "0.5",
    "--backdrop-background-height": "250px",
    "--bd-text-shadow-color-light": "255, 255, 255",
    "--bd-text-shadow-color": "0, 0, 0",
    "--bd-text-shadow-opacity-light": "0.6",
    "--bd-text-shadow-opacity": "0.6",
    "--card-background-fade": "1",
    "--card-fade-strength": "50%",
    "--word-background-fade": "0",
    "--word-fade-strength": "60%",
    "--enable-custom-offsets": "0",
    "--bd-word-bg-front-offset-1050": "5.45rem",
    "--bd-card-bg-front-offset-1050": "2.8rem",
    "--bd-word-bg-front-offset-mobile": "11.5rem",
    "--misc-info-default-expanded": "true",
    "--misc-info-above": "false",
    "--bold-misc-info": "0",
    "--misc-info-alignment": "center",
    "--misc-info-bg-visibility": "1",
    "--blur-nsfw-picture": "true",
    "--mute-nsfw-audio": "false",
    "--toggle-settings-key": "p",
    "--scene-replay-shortcut-key": "w",
    "--toggle-custom-dark-mode-key": "c",
    "--toggle-picture-lightbox-key": "q",
    "--toggle-picture-lightbox-grid-key": "shift+q",
    "--toggle-image-key": "l",
    "--text-light": "#020202",
    "--text": "#fcfcfc",
    "--light-highlight": "#E20033",
    "--dark-highlight": "#f5ca6c",
    "--light-devoiced-color": "RoyalBlue",
    "--dark-devoiced-color": "cornflowerBlue",
    "--freq-text-light": "rgba(105, 105, 105, 0.3)",
    "--freq-text": "rgba(255, 255, 255, 0.2)",
    "--tag-bg-light": "rgba(0, 0, 0, 0.03)",
    "--tag-bg": "rgba(0, 0, 0, 0.1)",
    "--tag-color-light": "rgba(105, 105, 105, 0.26)",
    "--tag-color": "rgba(255, 255, 255, 0.21)",
    "--tag-color-hover-light": "rgba(255, 255, 255, 1)",
    "--tag-color-hover": "rgba(255, 255, 255, 1)",
    "--external-links-bg-light": "rgba(0, 0, 0, 0.1)",
    "--external-links-bg": "rgba(0, 0, 0, 0.4)",
    "--misc-info-text-light": "rgba(105, 105, 105, 0.26)",
    "--misc-info-text": "rgba(255, 255, 255, 0.21)",
    "--misc-info-text-hover-light": "rgba(255, 255, 255, 1)",
    "--misc-info-text-hover": "rgba(255, 255, 255, 1)",
    "--misc-info-bg-light": "rgba(0, 0, 0, 0.03)",
    "--misc-info-bg": "rgba(0, 0, 0, 0.1)",
    "--misc-info-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--misc-info-bg-hover": "rgba(0, 0, 0, 0.3)",
    "--svg-color-light": "rgba(105, 105, 105, 0.3)",
    "--svg-color": "rgba(255, 255, 255, 0.2)",
    "--svg-hover-light": "rgba(255, 255, 255, 1)",
    "--svg-hover": "rgba(255, 255, 255, 1)",
    "--buttons-bg-light": "rgba(0, 0, 0, 0.03)",
    "--buttons-bg": "rgba(0, 0, 0, 0.1)",
    "--buttons-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--buttons-bg-hover": "rgba(0, 0, 0, 0.63)",
    "--background-light": "#f5f5f5",
    "--background": "#2e3440",
    "--card-bg-light": "rgba(255, 255, 255, 0.4)",
    "--card-bg": "rgba(0, 0, 0, 0.4)",
    "--card-shadow-light": "rgba(0, 0, 0, 0.05)",
    "--card-shadow": "rgba(0, 0, 0, 0.3)",
    "--lightbox-bg-light": "rgba(0, 0, 0, 0.8)",
    "--lightbox-bg": "rgba(0, 0, 0, 0.8)",
    "--pitch-position-bg-light": "rgba(255, 255, 255, 0.8)",
    "--pitch-position-bg": "rgba(0, 0, 0, 0.2)",
    "--pitch-red-light": "#D62839",
    "--pitch-red": "#F5436D",
    "--pitch-blue-light": "#3474FF",
    "--pitch-blue": "#39C1FF",
    "--pitch-orange-light": "#FF6E03",
    "--pitch-orange": "#fca311",
    "--pitch-green-light": "#2BAF7E",
    "--pitch-green": "#40D4A6",
    "--pitch-purple-light": "#8A5EDE",
    "--pitch-purple": "#afa2ff",
    "--word-bg-light": "rgba(0, 0, 0, 0.03)",
    "--word-bg": "rgba(0, 0, 0, 0.3)",
    "--picture-bg-light": "rgba(0, 0, 0, 0.03)",
    "--picture-bg": "rgba(0, 0, 0, 0.3)",
    "--notes-bg-light": "rgba(0, 0, 0, 0.03)",
    "--notes-bg": "rgba(0, 0, 0, 0.3)",
    "--definition-bg-light": "rgba(0, 0, 0, 0.03)",
    "--definition-bg": "rgba(0, 0, 0, 0.3)",
    "--frequency-bg-light": "rgba(255, 255, 255, 0.8)",
    "--frequency-bg": "rgba(0, 0, 0, 0.63)",
    "user-custom-css": ""
  },
  "_active": "My Preset 1"
}