{
  "Default": {
    "--settings-visibility": "1",
    "--main-bg-visibility": "1",
    "--main-bg-shadow-visibility": "1",
    "--custom-dark-mode-visibility": "1",
    "--audio-visibility": "1",
    "--freq-visibility": "1",
    "--tag-visibility": "1",
    "--external-links-visibility": "1",
    "--pitch-position-visibility": "1",
    "--settings-visibility-header": "1",
    "--main-bg-1050-visibility": "1",
    "--main-bg-shadow-1050-visibility": "0",
    "--custom-dm-header-visibility": "1",
    "--audio-header-visibility": "1",
    "--freq-header-visibility": "1",
    "--enable-animations": "true",
    "--word-sentence-default-expanded": "false",
    "--audio-sentence-default-expanded": "false",
    "--hint-default-expanded": "false",
    "--translation-default-expanded": "false",
    "--notes-default-expanded": "false",
    "--collect-glossary-images": "false",
    "--no-duplicate-kana": "false",
    "--mute-sentence-audio": "false",
    "--base-size": "clamp(19px, 3vw, 24px)",
    "--base-line-height": "1.5",
    "--bold-highlight": "0",
    "--serif": "\"Hiragino Mincho ProN\", \"Noto Serif JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sans": "\"Hiragino Mincho ProN\", \"Noto Serif JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sentence-alignment": "center",
    "--word-size-base": "2.5rem",
    "--word-size-4": "2.1rem",
    "--word-size-5": "2.0rem",
    "--word-size-6": "1.7rem",
    "--word-size-7": "1.6rem",
    "--word-size-8": "1.3rem",
    "--word-size-9": "1.15rem",
    "--reading-position": "below",
    "--dynamic-furigana-size": "0",
    "--furigana-size": "1rem",
    "--furigana-height": "0.0rem",
    "--sentence-furigana-display": "1",
    "--sentence-furigana-height": "0.0rem",
    "--sentence-size": "1.3rem",
    "--sentence-eng-size": "0.8rem",
    "--definition-size": "0.8rem",
    "--misc-info-size": "15px",
    "--tag-font-size": "0.7rem",
    "--frequency-size": "20px",
    "--frequency-content-size": "14px",
    "--border-radius-sm": "4px",
    "--border-radius-ms": "5px",
    "--border-radius-md": "10px",
    "--border-radius-lg": "12px",
    "--tag-border-radius": "5px",
    "--card-max-width": "800px",
    "--front-top-offset": "104px",
    "--back-top-offset": "26px",
    "--button-size": "20px",
    "--picture-height": "220px",
    "--picture-height-small": "330px",
    "--lightbox-nav-width": "100px",
    "--external-links-icon-size": "25px",
    "--frequency-max-height": "500px",
    "--base-transition": "0.3s ease",
    "--fast-transition": "0.2s ease",
    "--spacing-xs": "2px",
    "--spacing-sm": "3px",
    "--spacing-ms": "8px",
    "--spacing-md": "10px",
    "--spacing-lg": "15px",
    "--spacing-xl": "20px",
    "--spacing-xxl": "24px",
    "--spacing-xxxl": "34px",
    "--base-padding": "20px",
    "--dictionary-collapse": "1",
    "--dictionary-max-height": "390px",
    "--definition-title-visibility": "1",
    "--glossary-title-visibility": "1",
    "--dictionary-colorizer": "1",
    "--dict-bg-enabled": "1",
    "--dict-back-bg": "1",
    "--dict-bg-opacity": "0.03",
    "--dict-border-width": "5px",
    "--jitendex-hide-examples": "0",
    "--jitendex-hide-info-gloss": "0",
    "--jitendex-hide-xref": "0",
    "--jitendex-hide-graphic": "0",
    "--jitendex-hide-notes": "0",
    "--jitendex-hide-antonyms": "0",
    "--jitendex-hide-forms": "1",
    "--jitendex-hide-attribution": "1",
    "--pitch-style": "default",
    "--pitch-colors": "true",
    "--sentence-pitch-highlight": "false",
    "--only-kana-pitch-size": "0.08em",
    "--enable-kanji-hover": "true",
    "--kanji-hover-sentence-visibility": "1",
    "--kanji-hover-auto-quote": "true",
    "--kanji-hover-word-font": "var(--serif)",
    "--kanji-hover-word-size": "1rem",
    "--kanji-hover-word-reading-size": "0.65rem",
    "--kanji-hover-pitch-colors": "true",
    "--kanji-hover-pitch-highlight": "true",
    "--grid-gap": "var(--spacing-md)",
    "--grid-column-min-width": "390px",
    "--grid-order": "1",
    "--vertical-grid-order": "0",
    "--horizontal-grid-large": "1",
    "--vertical-grid-large": "0",
    "--horizontal-grid-medium": "1",
    "--vertical-grid-medium": "0",
    "--horizontal-grid-small": "0",
    "--vertical-grid-small": "1",
    "--enable-backdrop-layout": "0",
    "--backdrop-style": "1",
    "--backdrop-dynamic-height": "0",
    "--bd-card-bg-front-offset": "55px",
    "--bd-word-bg-front-offset": "119px",
    "--word-background-box": "0",
    "--backdrop-opacity": "0.5",
    "--backdrop-background-height": "250px",
    "--bd-text-shadow-color-light": "255, 255, 255",
    "--bd-text-shadow-color": "0, 0, 0",
    "--bd-text-shadow-opacity-light": "0.6",
    "--bd-text-shadow-opacity": "0.6",
    "--card-background-fade": "1",
    "--card-fade-strength": "50%",
    "--word-background-fade": "0",
    "--word-fade-strength": "60%",
    "--enable-custom-offsets": "0",
    "--bd-word-bg-front-offset-1050": "5.45rem",
    "--bd-card-bg-front-offset-1050": "2.8rem",
    "--bd-word-bg-front-offset-mobile": "11.5rem",
    "--misc-info-default-expanded": "false",
    "--misc-info-above": "false",
    "--bold-misc-info": "0",
    "--misc-info-alignment": "center",
    "--misc-info-bg-visibility": "1",
    "--blur-nsfw-picture": "true",
    "--mute-nsfw-audio": "true",
    "--toggle-settings-key": "p",
    "--scene-replay-shortcut-key": "w",
    "--toggle-custom-dark-mode-key": "c",
    "--toggle-picture-lightbox-key": "q",
    "--toggle-picture-lightbox-grid-key": "shift+q",
    "--toggle-image-key": "l",
    "--text-light": "#020202",
    "--text": "#fcfcfc",
    "--light-highlight": "#E20033",
    "--dark-highlight": "#FEC8D8",
    "--light-devoiced-color": "RoyalBlue",
    "--dark-devoiced-color": "cornflowerBlue",
    "--freq-text-light": "rgba(105, 105, 105, 0.3)",
    "--freq-text": "rgba(255, 255, 255, 0.2)",
    "--tag-bg-light": "rgba(0, 0, 0, 0.03)",
    "--tag-bg": "rgba(0, 0, 0, 0.1)",
    "--tag-color-light": "rgba(105, 105, 105, 0.26)",
    "--tag-color": "rgba(255, 255, 255, 0.21)",
    "--tag-color-hover-light": "rgba(255, 255, 255, 1)",
    "--tag-color-hover": "rgba(255, 255, 255, 1)",
    "--external-links-bg-light": "rgba(0, 0, 0, 0.1)",
    "--external-links-bg": "rgba(0, 0, 0, 0.4)",
    "--misc-info-text-light": "rgba(105, 105, 105, 0.26)",
    "--misc-info-text": "rgba(255, 255, 255, 0.21)",
    "--misc-info-text-hover-light": "rgba(255, 255, 255, 1)",
    "--misc-info-text-hover": "rgba(255, 255, 255, 1)",
    "--misc-info-bg-light": "rgba(0, 0, 0, 0.03)",
    "--misc-info-bg": "rgba(0, 0, 0, 0.1)",
    "--misc-info-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--misc-info-bg-hover": "rgba(0, 0, 0, 0.3)",
    "--svg-color-light": "rgba(105, 105, 105, 0.3)",
    "--svg-color": "rgba(255, 255, 255, 0.2)",
    "--svg-hover-light": "rgba(255, 255, 255, 1)",
    "--svg-hover": "rgba(255, 255, 255, 1)",
    "--buttons-bg-light": "rgba(0, 0, 0, 0.03)",
    "--buttons-bg": "rgba(0, 0, 0, 0.1)",
    "--buttons-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--buttons-bg-hover": "rgba(0, 0, 0, 0.63)",
    "--background-light": "#f5f5f5",
    "--background": "#2c2c2c",
    "--card-bg-light": "rgba(255, 255, 255, 0.4)",
    "--card-bg": "rgba(0, 0, 0, 0.4)",
    "--card-shadow-light": "rgba(0, 0, 0, 0.05)",
    "--card-shadow": "rgba(0, 0, 0, 0.3)",
    "--lightbox-bg-light": "rgba(0, 0, 0, 0.8)",
    "--lightbox-bg": "rgba(0, 0, 0, 0.8)",
    "--pitch-position-bg-light": "rgba(255, 255, 255, 0.8)",
    "--pitch-position-bg": "rgba(0, 0, 0, 0.2)",
    "--pitch-red-light": "#D62839",
    "--pitch-red": "#F5436D",
    "--pitch-blue-light": "#3474FF",
    "--pitch-blue": "#39C1FF",
    "--pitch-orange-light": "#FF6E03",
    "--pitch-orange": "#fca311",
    "--pitch-green-light": "#2BAF7E",
    "--pitch-green": "#40D4A6",
    "--pitch-purple-light": "#8A5EDE",
    "--pitch-purple": "#afa2ff",
    "--word-bg-light": "rgba(0, 0, 0, 0.03)",
    "--word-bg": "rgba(0, 0, 0, 0.3)",
    "--picture-bg-light": "rgba(0, 0, 0, 0.03)",
    "--picture-bg": "rgba(0, 0, 0, 0.3)",
    "--notes-bg-light": "rgba(0, 0, 0, 0.03)",
    "--notes-bg": "rgba(0, 0, 0, 0.3)",
    "--definition-bg-light": "rgba(0, 0, 0, 0.03)",
    "--definition-bg": "rgba(0, 0, 0, 0.3)",
    "--frequency-bg-light": "rgba(255, 255, 255, 0.8)",
    "--frequency-bg": "rgba(0, 0, 0, 0.63)",
    "user-custom-css": ""
  },
  "My Preset 1": {
    "--settings-visibility": "1",
    "--main-bg-visibility": "1",
    "--main-bg-shadow-visibility": "1",
    "--custom-dark-mode-visibility": "1",
    "--audio-visibility": "1",
    "--freq-visibility": "1",
    "--tag-visibility": "1",
    "--external-links-visibility": "1",
    "--pitch-position-visibility": "1",
    "--settings-visibility-header": "1",
    "--main-bg-1050-visibility": "1",
    "--main-bg-shadow-1050-visibility": "1",
    "--custom-dm-header-visibility": "1",
    "--audio-header-visibility": "1",
    "--freq-header-visibility": "1",
    "--enable-animations": "false",
    "--word-sentence-default-expanded": "false",
    "--audio-sentence-default-expanded": "false",
    "--hint-default-expanded": "false",
    "--translation-default-expanded": "false",
    "--notes-default-expanded": "true",
    "--collect-glossary-images": "true",
    "--no-duplicate-kana": "true",
    "--mute-sentence-audio": "false",
    "--base-size": "clamp(19px, 3vw, 24px)",
    "--base-line-height": "1.5",
    "--bold-highlight": "1",
    "--serif": "\"Hiragino Mincho ProN\", \"Noto Serif JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sans": "\"Hiragino Mincho ProN\", \"Noto Serif JP\", notoserifjp, \"Yu Mincho\", serif",
    "--sentence-alignment": "center",
    "--word-size-base": "2.5rem",
    "--word-size-4": "2.1rem",
    "--word-size-5": "2rem",
    "--word-size-6": "1.7rem",
    "--word-size-7": "1.6rem",
    "--word-size-8": "1.3rem",
    "--word-size-9": "1.15rem",
    "--reading-position": "below",
    "--dynamic-furigana-size": "0",
    "--furigana-size": "1rem",
    "--furigana-height": "0rem",
    "--sentence-furigana-display": "1",
    "--sentence-furigana-height": "0rem",
    "--sentence-size": "1.3rem",
    "--sentence-eng-size": "0.8rem",
    "--definition-size": "0.8rem",
    "--misc-info-size": "15px",
    "--tag-font-size": "0.7rem",
    "--frequency-size": "20px",
    "--frequency-content-size": "14px",
    "--border-radius-sm": "4px",
    "--border-radius-ms": "5px",
    "--border-radius-md": "10px",
    "--border-radius-lg": "12px",
    "--tag-border-radius": "5px",
    "--card-max-width": "800px",
    "--front-top-offset": "104px",
    "--back-top-offset": "26px",
    "--button-size": "20px",
    "--picture-height": "220px",
    "--picture-height-small": "330px",
    "--lightbox-nav-width": "100px",
    "--external-links-icon-size": "25px",
    "--frequency-max-height": "500px",
    "--base-transition": "0.3s ease",
    "--fast-transition": "0.2s ease",
    "--spacing-xs": "2px",
    "--spacing-sm": "3px",
    "--spacing-ms": "8px",
    "--spacing-md": "10px",
    "--spacing-lg": "15px",
    "--spacing-xl": "20px",
    "--spacing-xxl": "24px",
    "--spacing-xxxl": "34px",
    "--base-padding": "20px",
    "--dictionary-collapse": "1",
    "--dictionary-max-height": "390px",
    "--definition-title-visibility": "1",
    "--glossary-title-visibility": "1",
    "--dictionary-colorizer": "1",
    "--dict-bg-enabled": "1",
    "--dict-back-bg": "1",
    "--dict-bg-opacity": "0.03",
    "--dict-border-width": "5px",
    "--jitendex-hide-examples": "0",
    "--jitendex-hide-info-gloss": "0",
    "--jitendex-hide-xref": "0",
    "--jitendex-hide-graphic": "0",
    "--jitendex-hide-notes": "0",
    "--jitendex-hide-antonyms": "0",
    "--jitendex-hide-forms": "1",
    "--jitendex-hide-attribution": "1",
    "--pitch-style": "alt",
    "--pitch-colors": "true",
    "--sentence-pitch-highlight": "true",
    "--only-kana-pitch-size": "0.08em",
    "--enable-kanji-hover": "true",
    "--kanji-hover-sentence-visibility": "1",
    "--kanji-hover-auto-quote": "true",
    "--kanji-hover-word-font": "var(--serif)",
    "--kanji-hover-word-size": "1rem",
    "--kanji-hover-word-reading-size": "0.65rem",
    "--kanji-hover-pitch-colors": "true",
    "--kanji-hover-pitch-highlight": "true",
    "--grid-gap": "var(--spacing-lg)",
    "--grid-column-min-width": "390px",
    "--grid-order": "1",
    "--vertical-grid-order": "0",
    "--horizontal-grid-large": "1",
    "--vertical-grid-large": "0",
    "--horizontal-grid-medium": "1",
    "--vertical-grid-medium": "0",
    "--horizontal-grid-small": "0",
    "--vertical-grid-small": "1",
    "--enable-backdrop-layout": "0",
    "--backdrop-style": "1",
    "--backdrop-dynamic-height": "0",
    "--bd-card-bg-front-offset": "55px",
    "--bd-word-bg-front-offset": "119px",
    "--word-background-box": "0",
    "--backdrop-opacity": "0.5",
    "--backdrop-background-height": "250px",
    "--bd-text-shadow-color-light": "255, 255, 255",
    "--bd-text-shadow-color": "0, 0, 0",
    "--bd-text-shadow-opacity-light": "0.6",
    "--bd-text-shadow-opacity": "0.6",
    "--card-background-fade": "1",
    "--card-fade-strength": "50%",
    "--word-background-fade": "0",
    "--word-fade-strength": "60%",
    "--enable-custom-offsets": "0",
    "--bd-word-bg-front-offset-1050": "5.45rem",
    "--bd-card-bg-front-offset-1050": "2.8rem",
    "--bd-word-bg-front-offset-mobile": "11.5rem",
    "--misc-info-default-expanded": "true",
    "--misc-info-above": "false",
    "--bold-misc-info": "0",
    "--misc-info-alignment": "center",
    "--misc-info-bg-visibility": "1",
    "--blur-nsfw-picture": "true",
    "--mute-nsfw-audio": "false",
    "--toggle-settings-key": "p",
    "--scene-replay-shortcut-key": "w",
    "--toggle-custom-dark-mode-key": "c",
    "--toggle-picture-lightbox-key": "q",
    "--toggle-picture-lightbox-grid-key": "shift + q",
    "--toggle-image-key": "M",
    "--text-light": "#020202",
    "--text": "#f1f1f1",
    "--light-highlight": "#E20033",
    "--dark-highlight": "#fcee0a",
    "--light-devoiced-color": "RoyalBlue",
    "--dark-devoiced-color": "#00f0ff",
    "--freq-text-light": "rgba(105, 105, 105, 0.3)",
    "--freq-text": "#8f8f8f",
    "--tag-bg-light": "rgba(0, 0, 0, 0.03)",
    "--tag-bg": "#2a0b35",
    "--tag-color-light": "rgba(105, 105, 105, 0.26)",
    "--tag-color": "#d6d6d6",
    "--tag-color-hover-light": "rgba(255, 255, 255, 1)",
    "--tag-color-hover": "#ffffff",
    "--external-links-bg-light": "rgba(0, 0, 0, 0.1)",
    "--external-links-bg": "#10141b",
    "--misc-info-text-light": "rgba(105, 105, 105, 0.26)",
    "--misc-info-text": "#d0d0d0",
    "--misc-info-text-hover-light": "rgba(255, 255, 255, 1)",
    "--misc-info-text-hover": "#ffffff",
    "--misc-info-bg-light": "rgba(0, 0, 0, 0.03)",
    "--misc-info-bg": "#10141b",
    "--misc-info-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--misc-info-bg-hover": "#ff0055",
    "--svg-color-light": "rgba(105, 105, 105, 0.3)",
    "--svg-color": "#00f0ff",
    "--svg-hover-light": "rgba(255, 255, 255, 1)",
    "--svg-hover": "#fcee0a",
    "--buttons-bg-light": "rgba(0, 0, 0, 0.03)",
    "--buttons-bg": "#10141b",
    "--buttons-bg-hover-light": "rgba(0, 0, 0, 0.63)",
    "--buttons-bg-hover": "#fcee0a",
    "--background-light": "#f5f5f5",
    "--background": "#040405",
    "--card-bg-light": "rgba(255, 255, 255, 0.4)",
    "--card-bg": "#09090c",
    "--card-shadow-light": "rgba(0, 0, 0, 0.05)",
    "--card-shadow": "rgba(255, 0, 85, 0.22)",
    "--lightbox-bg-light": "rgba(0, 0, 0, 0.8)",
    "--lightbox-bg": "#040405",
    "--pitch-position-bg-light": "rgba(255, 255, 255, 0.8)",
    "--pitch-position-bg": "#35003b",
    "--pitch-red-light": "#D62839",
    "--pitch-red": "#ff0055",
    "--pitch-blue-light": "#3474FF",
    "--pitch-blue": "#00f0ff",
    "--pitch-orange-light": "#FF6E03",
    "--pitch-orange": "#ff9f1c",
    "--pitch-green-light": "#2BAF7E",
    "--pitch-green": "#39ff14",
    "--pitch-purple-light": "#8A5EDE",
    "--pitch-purple": "#bd00ff",
    "--word-bg-light": "rgba(0, 0, 0, 0.03)",
    "--word-bg": "#11131a",
    "--picture-bg-light": "rgba(0, 0, 0, 0.03)",
    "--picture-bg": "#11131a",
    "--notes-bg-light": "rgba(0, 0, 0, 0.03)",
    "--notes-bg": "#14161d",
    "--definition-bg-light": "rgba(0, 0, 0, 0.03)",
    "--definition-bg": "#14161d",
    "--frequency-bg-light": "rgba(255, 255, 255, 0.8)",
    "--frequency-bg": "#2a0b35",
    "user-custom-css": "/* ============================================\n   RESPONSIVE: Samsung Galaxy A26 & Small Phones\n   (viewport ~360-412px)\n   ============================================ */\n\n/* --- External Links: Allow wrapping on narrow screens --- */\n@media (max-width: 500px) {\n  .external-links {\n    flex-wrap: wrap;\n    justify-content: flex-end;\n    gap: 3px;\n    margin-left: 0;\n    width: 100%;\n  }\n\n  .tags-and-links-wrapper {\n    flex-direction: column;\n    gap: 5px;\n  }\n\n  .external-links a {\n    min-width: 40px;\n    min-height: 40px;\n    align-items: center;\n    justify-content: center;\n    border-radius: 5px !important;\n    padding: 6px !important;\n  }\n\n  .external-links a:first-child,\n  .external-links a:last-child {\n    border-radius: 5px !important;\n  }\n\n  .external-links img {\n    width: clamp(18px, 5vw, var(--base-size)) !important;\n    height: clamp(18px, 5vw, var(--base-size)) !important;\n  }\n}\n\n/* --- Core layout adjustments for small phones --- */\n@media (max-width: 420px) {\n  /* Reduce base padding to reclaim screen space */\n  .front,\n  .back {\n    padding: 12px !important;\n  }\n\n  /* Tighter sentence container margins */\n  .sentence-container {\n    margin-left: 2px;\n    margin-right: 2px;\n  }\n\n  /* Definition/glossary box padding */\n  .glossary-box,\n  .definition-box {\n    padding: var(--spacing-md) !important;\n  }\n\n  /* Misc info padding */\n  .misc-info {\n    padding-left: var(--spacing-ms) !important;\n    padding-right: var(--spacing-ms) !important;\n  }\n\n  /* Tags tighter fit */\n  .tags {\n    padding: 4px 8px;\n    font-size: 0.75rem;\n  }\n\n  /* Header gap on mobile */\n  .header {\n    gap: 4px !important;\n  }\n\n  /* Front header buttons closer together */\n  .front > .header {\n    gap: 4px;\n    margin-bottom: 4px;\n  }\n\n  /* Lightbox nav narrower for small screen */\n  .lightbox .lightbox-nav {\n    width: 60px;\n  }\n\n  /* Lightbox grid smaller tiles */\n  .lightbox-grid {\n    grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));\n    gap: 6px;\n    padding: 10px;\n  }\n\n  /* Notes card grid — single column */\n  .notes-card-grid {\n    grid-template-columns: 1fr;\n    gap: var(--spacing-ms);\n  }\n\n  /* Notes details grid — single column */\n  .notes-details-grid {\n    grid-template-columns: 1fr;\n  }\n\n  /* Legend modal full width */\n  .notes-legend-modal {\n    max-width: 98vw;\n  }\n\n  .notes-legend-term {\n    white-space: normal;\n    min-width: 70px;\n  }\n\n  /* Grammar tooltip */\n  #grammar-tooltip {\n    max-width: 95vw;\n  }\n\n  /* Word size scaling for small screens */\n  .mobile-word-layout > .background-box {\n    padding-top: 18px;\n    padding-bottom: 22px;\n  }\n\n  /* Picture height adjustment */\n  .picture-container img {\n    max-height: 250px;\n  }\n\n  /* Frequency box */\n  .frequency-box {\n    font-size: 0.8rem;\n  }\n\n  /* Notes card smaller */\n  .notes-card {\n    padding: var(--spacing-ms) var(--spacing-md);\n  }\n\n  .notes-card-word {\n    font-size: 1.15rem;\n  }\n\n  .notes-card-meaning {\n    font-size: 0.78rem;\n  }\n}\n\n/* --- Extra-narrow phones (360px and below) --- */\n@media (max-width: 370px) {\n  .front,\n  .back {\n    padding: 10px !important;\n  }\n\n  .external-links a {\n    padding: 5px !important;\n    min-width: 36px;\n    min-height: 36px;\n  }\n\n  .back .background-box {\n    padding-left: 4px;\n    padding-right: 4px;\n  }\n\n  .glossary-box,\n  .definition-box {\n    padding: var(--spacing-ms) !important;\n  }\n\n  /* Sentence font size slightly smaller to prevent overflow */\n  #sentence,\n  #sentence-audio {\n    font-size: clamp(0.85rem, 4vw, var(--sentence-size));\n  }\n}\n\n/* --- Settings modal responsive for Galaxy A26 --- */\n@media (max-width: 420px) {\n  .senren-prompt-box {\n    width: 95vw !important;\n    padding: 16px !important;\n    border-radius: 16px;\n  }\n\n  .senren-prompt-input {\n    padding: 10px 12px;\n    font-size: 14px;\n  }\n\n  .senren-prompt-btn {\n    padding: 10px 0 !important;\n    font-size: 13px;\n  }\n\n  .senren-dialog {\n    border-radius: 0;\n    max-height: 100vh;\n    max-width: 100vw;\n    height: 100vh;\n    width: 100vw;\n  }\n\n  .senren-header {\n    padding: 10px 14px;\n  }\n\n  .senren-header h2 {\n    font-size: 15px;\n  }\n\n  .senren-panel {\n    padding: 12px !important;\n  }\n\n  .senren-row {\n    gap: 6px;\n  }\n}"
  },
  "_active": "My Preset 1"
}